-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "price" SET DEFAULT 0.10;

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "gold" SET DEFAULT 0,
ALTER COLUMN "loses" SET DEFAULT 0,
ALTER COLUMN "wins" SET DEFAULT 0;
